//! `tatara-rust-verify` — auto-emit a `consumer-verify/` crate per
//! `MacroCatalogSpec`. The catalog's own verification harness is
//! itself generated — every emitted derive proves itself in a
//! `cargo test` run alongside the N decorated repos.
//!
//! **★★ TYPED EMISSION.** Every smoke renderer builds a
//! `proc_macro2::TokenStream` via `quote!{}`; the umbrella `lib.rs` is
//! assembled from those module token streams and rendered through ONE
//! chokepoint — [`render_file`] (`syn::parse2::<syn::File>` +
//! `prettyplease::unparse`). No `format!()`/`push_str` of Rust syntax
//! remains. The `Cargo.toml` is built as a typed
//! [`tatara_rust_ast::CargoManifest`] and serialized via `toml::to_string`.
//!
//! Per-kind verifier strategy:
//!   - `Derive` (simple marker)       → struct with `#[derive(Trait)]`
//!                                      asserts it compiles.
//!   - `PerField` (getter/setter/builder) → struct with 2 fields,
//!                                      `#[derive(Trait)]`, calls each
//!                                      generated method.
//!   - `PerVariant` (predicate)       → enum with 3 variants,
//!                                      `#[derive(Trait)]`, calls each
//!                                      predicate.
//!   - `ProcAttr` / `ProcFn` / `MacroRules` / `Composite`
//!                                    → MVP: emit `let _ = …;` smoke
//!                                      that proves the macro is
//!                                      importable. Specialized
//!                                      verifiers land as follow-up
//!                                      per-kind variants.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use tatara_rust_ast::cargo_manifest::{CargoManifest, Dep, DetailedDep, Lib, Package};
use tatara_rust_ast::{CrateScaffold, FileEntry};
use tatara_rust_catalog::{CatalogEntry, CatalogSpec, MacroCatalogSpec, VerifierHint};
use tatara_rust_derive::{
    ClosedAxisSpec, EnumFoldDeriveSpec, KindRoundTripSpec, NewtypeDeriveSpec, PerFieldDeriveSpec,
    PerVariantDeriveSpec, VerificationMatrixSpec,
};

/// Render a complete `consumer-verify/` Cargo crate scaffold. The
/// caller writes it next to the N decorated repos so that
/// `cargo test -p consumer-verify` exercises every emitted derive.
///
/// `repo_path_template` maps each entry's crate name to the path
/// string the consumer's `Cargo.toml` should use to reach the
/// generated repo — typically `format!("../{name}")` when consumer
/// sits as a workspace member next to the repos.
#[must_use]
pub fn build_consumer_verify(
    catalog: &MacroCatalogSpec,
    repo_path_template: impl Fn(&str) -> String,
) -> CrateScaffold {
    let mut s = CrateScaffold::new("consumer-verify", "0.1.0");
    s.add_file("Cargo.toml", render_cargo_toml(catalog, &repo_path_template));
    s.add_file("src/lib.rs", render_lib_rs(catalog));
    s
}

// ─────────────────────────────────────────────────────────────────────
// The one and only Rust-source chokepoint
// ─────────────────────────────────────────────────────────────────────

/// Render a `TokenStream` of crate-level items into a formatted source
/// string. Parses through `syn::File` (so malformed emission is a
/// compile-time-of-the-emitter panic, not silent garbage), then
/// `prettyplease::unparse`. The ★★ TYPED EMISSION single render surface.
fn render_file(items: TokenStream) -> String {
    let parsed: syn::File =
        syn::parse2(items).expect("emitted consumer-verify lib.rs must parse as syn::File");
    prettyplease::unparse(&parsed)
}

/// Just the lib.rs body — useful for snapshot tests + diagnostics.
#[must_use]
pub fn render_lib_rs(catalog: &MacroCatalogSpec) -> String {
    let modules: Vec<TokenStream> = catalog.entries.iter().map(render_entry_module).collect();
    let file = quote! {
        #![doc = "Generated by tatara-rust-verify — exercises every macro in the catalog."]
        #![doc = "One test module per entry."]
        #![doc = ""]
        #![doc = "This file is RE-GENERATED on every catalog instantiate; do not edit by hand."]

        #(#modules)*
    };
    render_file(file)
}

fn render_entry_module(entry: &CatalogEntry) -> TokenStream {
    let mod_ident = format_ident!("{}", entry.crate_name.replace('-', "_"));
    let doc = format!(
        "Verifier for catalog entry `{}` (kind: {}).",
        entry.crate_name,
        entry.spec.kind_label()
    );
    let body = render_per_kind_body(entry);
    quote! {
        #[doc = #doc]
        pub mod #mod_ident {
            #body
        }
    }
}

fn render_per_kind_body(entry: &CatalogEntry) -> TokenStream {
    let extern_name = entry.crate_name.replace('-', "_");

    // **Explicit hint takes precedence.** Removes the fragility of
    // template-text substring matching for catalogs that opt in.
    if let Some(hint) = entry.verifier_hint {
        let trait_name = entry.spec.trait_name_for_verifier().unwrap_or("Unknown");
        return render_by_hint(hint, &extern_name, trait_name);
    }

    // Back-compat path: infer from spec shape + template text.
    match &entry.spec {
        CatalogSpec::Derive { spec } => render_marker_smoke(&extern_name, &spec.trait_name.0),
        CatalogSpec::PerField { spec } => render_per_field_smoke(&extern_name, spec),
        CatalogSpec::PerVariant { spec } => render_per_variant_smoke(&extern_name, spec),
        CatalogSpec::Newtype { spec } => render_newtype_smoke(&extern_name, spec),
        CatalogSpec::EnumFold { spec } => render_enum_fold_smoke(&extern_name, spec),
        CatalogSpec::ProcAttr { spec } => render_proc_attr_smoke(&extern_name, &spec.macro_name.0),
        CatalogSpec::ProcFn { spec } => render_proc_fn_smoke(&extern_name, &spec.macro_name.0),
        CatalogSpec::MacroRules { spec } => {
            render_macro_rules_smoke(&extern_name, &spec.macro_name.0)
        }
        CatalogSpec::Composite { spec } => render_marker_smoke(&extern_name, &spec.bundle_name.0),
        CatalogSpec::KindRoundTrip { spec } => render_kind_round_trip_smoke(&extern_name, spec),
        CatalogSpec::VerificationMatrix { spec } => {
            render_verification_matrix_smoke(&extern_name, spec)
        }
        CatalogSpec::ClosedAxis { spec } => render_closed_axis_smoke(&extern_name, spec),
    }
}

/// Smoke test for a ClosedAxis derive: a unit enum with the
/// `Copy + Eq + Hash` bounds the `shikumi::ClosedAxis` trait requires,
/// `#[derive(ClosedAxis)]`, then asserts BOTH halves of the derive
/// output — the inherent `Self::ALL` AND the `impl ::shikumi::ClosedAxis`
/// associated `ALL`. The umbrella `Cargo.toml` now carries the shikumi
/// git dep (added by [`render_cargo_toml`] when any entry is a
/// `ClosedAxis`), so this gate proves the FULL derive, not just the
/// inherent constant.
fn render_closed_axis_smoke(extern_name: &str, spec: &ClosedAxisSpec) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{}", spec.trait_name.0);
    quote! {
        use #extern_id::#trait_id;

        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, #trait_id)]
        pub enum Sample {
            Block,
            Bar,
            Underline,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn inherent_all_enumerates_every_variant() {
                assert_eq!(Sample::ALL.len(), 3);
                assert!(Sample::ALL.iter().any(|v| matches!(v, Sample::Block)));
                assert!(Sample::ALL.iter().any(|v| matches!(v, Sample::Bar)));
                assert!(Sample::ALL.iter().any(|v| matches!(v, Sample::Underline)));
            }

            #[test]
            fn trait_impl_all_matches_inherent_all() {
                // The shikumi git dep is present, so the impl half is
                // exercised: the trait-associated ALL must equal the
                // inherent ALL (both enumerate every variant).
                assert_eq!(<Sample as ::shikumi::ClosedAxis>::ALL, Sample::ALL);
            }
        }
    }
}

/// Smoke test for a VerificationMatrix macro crate: import both macros,
/// declare a 3-row table, drive a passing exercise closure through
/// `verification_matrix!`, and gate coverage with `matrix_covers_all!`.
/// Macro names come from the spec so a renamed surface still verifies.
fn render_verification_matrix_smoke(
    extern_name: &str,
    spec: &VerificationMatrixSpec,
) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let matrix_id = format_ident!("{}", spec.matrix_macro);
    let covers_id = format_ident!("{}", spec.covers_macro);
    quote! {
        pub use #extern_id::{#matrix_id, #covers_id};

        #[derive(Debug)]
        pub struct Row {
            pub name: &'static str,
            pub input: u32,
            pub doubled: u32,
        }

        pub const ROWS: &[Row] = &[
            Row { name: "one", input: 1, doubled: 2 },
            Row { name: "two", input: 2, doubled: 4 },
            Row { name: "three", input: 3, doubled: 6 },
        ];

        #matrix_id! {
            name = every_row_doubles,
            rows = ROWS,
            run = |r: &Row| -> ::std::result::Result<(), ::std::string::String> {
                if r.input * 2 == r.doubled {
                    ::std::result::Result::Ok(())
                } else {
                    ::std::result::Result::Err(
                        ::std::format!("{} != {}", r.input * 2, r.doubled),
                    )
                }
            },
        }

        #covers_id! {
            name = rows_cover_all,
            rows = ROWS,
            covers = 3usize,
        }
    }
}

/// Smoke test for a KindRoundTrip derive: a Sample enum using the spec's
/// helper attr + a test asserting the inverse-table property holds (string
/// always; byte too when `with_byte`). Method/attr names come from the
/// spec so a renamed surface still verifies.
fn render_kind_round_trip_smoke(extern_name: &str, spec: &KindRoundTripSpec) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{}", spec.trait_name.0);
    let attr_id = format_ident!("{}", spec.helper_attr);
    let as_str_id = format_ident!("{}", spec.as_str_method);
    let from_str_id = format_ident!("{}", spec.from_str_method);
    if spec.with_byte {
        let as_byte_id = format_ident!("{}", spec.as_byte_method);
        let from_byte_id = format_ident!("{}", spec.from_byte_method);
        quote! {
            use #extern_id::#trait_id;

            #[derive(Debug, PartialEq, Clone, Copy, #trait_id)]
            pub enum Sample {
                #[#attr_id(name = "alpha", byte = 97)]
                Alpha,
                #[#attr_id(name = "beta", alias = "b", byte = 98)]
                Beta,
            }

            #[cfg(test)]
            mod tests {
                use super::*;
                #[test]
                fn string_and_byte_round_trip() {
                    assert_eq!(Sample::Alpha.#as_str_id(), "alpha");
                    assert_eq!(Sample::Alpha.#as_byte_id(), 97u8);
                    assert_eq!(Sample::#from_str_id("b"), Some(Sample::Beta));
                    assert_eq!(Sample::#from_byte_id(98), Some(Sample::Beta));
                    assert_eq!(Sample::#from_str_id("nope"), None);
                    for v in [Sample::Alpha, Sample::Beta] {
                        assert_eq!(Sample::#from_str_id(v.#as_str_id()), Some(v));
                        assert_eq!(Sample::#from_byte_id(v.#as_byte_id()), Some(v));
                    }
                }
            }
        }
    } else {
        quote! {
            use #extern_id::#trait_id;

            #[derive(Debug, PartialEq, Clone, Copy, #trait_id)]
            pub enum Sample {
                #[#attr_id(name = "alpha")]
                Alpha,
                #[#attr_id(name = "beta", alias = "b")]
                Beta,
                Gamma,
            }

            #[cfg(test)]
            mod tests {
                use super::*;
                #[test]
                fn string_round_trip() {
                    assert_eq!(Sample::Alpha.#as_str_id(), "alpha");
                    assert_eq!(Sample::Gamma.#as_str_id(), "Gamma");
                    assert_eq!(Sample::#from_str_id("b"), Some(Sample::Beta));
                    assert_eq!(Sample::#from_str_id("nope"), None);
                    for v in [Sample::Alpha, Sample::Beta, Sample::Gamma] {
                        assert_eq!(Sample::#from_str_id(v.#as_str_id()), Some(v));
                    }
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Explicit-hint dispatcher
// ─────────────────────────────────────────────────────────────────────

/// Render a smoke-test body given an explicit `VerifierHint`. Used when
/// the catalog entry opts out of inferred classification.
///
/// The contract: every `VerifierHint` variant maps to exactly one
/// `render_*_smoke` function. Adding a new strategy is a 2-step edit
/// (new variant + new match arm here).
fn render_by_hint(hint: VerifierHint, extern_name: &str, trait_name: &str) -> TokenStream {
    match hint {
        VerifierHint::CompileOnly => render_compile_only_smoke(extern_name, trait_name),
        VerifierHint::PerFieldGetter => render_getter_smoke(extern_name, trait_name),
        VerifierHint::PerFieldSetter => render_setter_smoke(extern_name, trait_name),
        VerifierHint::PerFieldWithBuilder => render_with_builder_smoke(extern_name, trait_name),
        VerifierHint::PerFieldAsMut => render_asmut_smoke(extern_name, trait_name),
        VerifierHint::PerFieldReplace => render_replace_smoke(extern_name, trait_name),
        VerifierHint::PerFieldTake => render_take_smoke(extern_name, trait_name),
        VerifierHint::PerFieldInvalidatingSetter => {
            render_invalidating_setter_smoke(extern_name, trait_name)
        }
        VerifierHint::PerVariantIsVariant => {
            // Existing per-variant smoke is parameterized by template/method_tpl;
            // for hint dispatch we render the canonical predicate body directly.
            render_isvariant_predicate_smoke(extern_name, trait_name)
        }
        VerifierHint::NewtypeImplFrom => render_impl_from_smoke(extern_name, trait_name),
        VerifierHint::NewtypeAsRef => render_asref_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeDeref => render_deref_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeInner => render_inner_newtype_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldAllVariants => render_all_variants_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldVariantCount => render_variant_count_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldVariantNames => render_variant_names_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldVariantStr => render_variant_str_smoke(extern_name, trait_name),
        VerifierHint::PerFieldOwned => render_owned_smoke(extern_name, trait_name),
        VerifierHint::NewtypeBorrow => render_borrow_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeBorrowMut => render_borrow_mut_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeDerefMut => render_deref_mut_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeDisplay => render_display_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeDefault => render_default_newtype_smoke(extern_name, trait_name),
        VerifierHint::PerFieldReset => render_reset_smoke(extern_name, trait_name),
        VerifierHint::PerFieldSwap => render_swap_smoke(extern_name, trait_name),
    }
}

/// `pub fn reset_<field>(&mut self) where <T>: Default` smoke.
fn render_reset_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(Default, #trait_id)]
        pub struct Sample {
            pub host: String,
            pub port: u16,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn reset_field_returns_field_to_default() {
                let mut s = Sample { host: "abc".into(), port: 443 };
                s.reset_host();
                assert_eq!(s.host, "");
                assert_eq!(s.port, 443, "untouched fields stay");
                s.reset_port();
                assert_eq!(s.port, 0);
            }
        }
    }
}

/// `pub fn swap_<field>(&mut self, other: &mut Self)` smoke.
fn render_swap_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub host: String,
            pub port: u16,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn swap_field_exchanges_between_instances() {
                let mut a = Sample { host: "a".into(), port: 1 };
                let mut b = Sample { host: "b".into(), port: 2 };
                a.swap_host(&mut b);
                assert_eq!(a.host, "b");
                assert_eq!(b.host, "a");
                assert_eq!(a.port, 1, "untouched fields stay");
                assert_eq!(b.port, 2);
            }
        }
    }
}

/// `pub fn into_<field>(self) -> <T>` consuming-getter smoke.
fn render_owned_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub host: String,
            pub port: u16,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn into_field_consumes_and_returns_value() {
                let s = Sample { host: "h".into(), port: 443 };
                let h = s.into_host();
                assert_eq!(h, "h");
            }
        }
    }
}

/// Newtype `Borrow<Inner>` smoke.
fn render_borrow_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;
        use ::std::borrow::Borrow;

        #[derive(#trait_id)]
        pub struct W(pub String);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn borrow_returns_inner_ref() {
                let w = W("hi".into());
                let inner: &String = w.borrow();
                assert_eq!(inner, "hi");
            }
        }
    }
}

/// Newtype `BorrowMut<Inner>` smoke. std requires `BorrowMut: Borrow`,
/// so the consumer must hand-impl Borrow OR derive a sibling that
/// provides it; we hand-impl here to keep the smoke self-contained.
fn render_borrow_mut_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;
        use ::std::borrow::{Borrow, BorrowMut};

        #[derive(#trait_id)]
        pub struct W(pub String);
        impl Borrow<String> for W {
            fn borrow(&self) -> &String { &self.0 }
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn borrow_mut_returns_inner_mut_ref() {
                let mut w = W("hi".into());
                let inner: &mut String = <W as BorrowMut<String>>::borrow_mut(&mut w);
                inner.push('!');
                assert_eq!(w.0, "hi!");
            }
        }
    }
}

/// Newtype `DerefMut` smoke (pairs with NewtypeDeref — caller must
/// also derive that or hand-impl Deref since DerefMut requires it).
fn render_deref_mut_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;
        use ::std::ops::{Deref, DerefMut};

        pub struct W(pub String);
        impl Deref for W {
            type Target = String;
            fn deref(&self) -> &String { &self.0 }
        }
        impl ::std::ops::DerefMut for W {
            fn deref_mut(&mut self) -> &mut String { &mut self.0 }
        }

        // The actual derive smoke — apply to a separate type via the macro.
        #[derive(#trait_id)]
        pub struct V(pub String);
        impl Deref for V {
            type Target = String;
            fn deref(&self) -> &String { &self.0 }
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn deref_mut_works_via_macro() {
                let mut v = V("hi".into());
                v.push('!');
                assert_eq!(v.0, "hi!");
            }
        }
    }
}

/// Newtype `Display` (delegates to inner) smoke.
fn render_display_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct W(pub String);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn display_delegates_to_inner() {
                let w = W("hi".into());
                assert_eq!(format!("{w}"), "hi");
            }
        }
    }
}

/// Newtype `Default where Inner: Default` smoke.
fn render_default_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct W(pub String);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn default_forwards_to_inner() {
                let w = W::default();
                assert_eq!(w.0, "");
            }
        }
    }
}

/// Enum-fold `as_str() -> &'static str` (per-variant name) smoke.
fn render_variant_str_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub enum Status { Active, Pending, Done }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn as_str_returns_variant_name() {
                assert_eq!(Status::Active.as_str(), "Active");
                assert_eq!(Status::Pending.as_str(), "Pending");
                assert_eq!(Status::Done.as_str(), "Done");
            }
        }
    }
}

/// Canonical InvalidatingSetter smoke — sample struct includes
/// `last_seqno: u64` (the consumer-contract signal field), and marks
/// the two opt-in fields with `#[invalidating_setter]` per the
/// derive's `field_attribute` contract.
fn render_invalidating_setter_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(Default, #trait_id)]
        pub struct Sample {
            #[invalidating_setter]
            pub host: String,
            #[invalidating_setter]
            pub port: u16,
            pub last_seqno: u64,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn invalidating_setters_store_value_and_reset_seqno() {
                let mut s = Sample::default();
                s.last_seqno = 42;
                s.set_host("h".into());
                assert_eq!(s.host, "h");
                assert_eq!(s.last_seqno, 0, "set_host must reset seqno");

                s.last_seqno = 99;
                s.set_port(443);
                assert_eq!(s.port, 443);
                assert_eq!(s.last_seqno, 0, "set_port must reset seqno");
            }

            #[test]
            fn signal_field_does_not_get_a_setter() {
                // If `set_last_seqno` were generated, the trait would
                // shadow direct assignment — but the macro skips the
                // signal field. Confirm by direct access.
                let mut s = Sample::default();
                s.last_seqno = 7;
                assert_eq!(s.last_seqno, 7);
            }
        }
    }
}

/// Canonical IsVariant predicate smoke (extracted from `render_per_variant_smoke`'s
/// is-predicate branch so the hint dispatcher can call it directly).
fn render_isvariant_predicate_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub enum Sample {
            Started,
            Stopped(String),
            Tick { ms: u64 },
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn predicate_returns_true_only_for_own_variant() {
                let s = Sample::Started;
                assert!(s.is_started());
                assert!(!s.is_stopped());
                assert!(!s.is_tick());
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Per-kind verifier strategies (inferred-classifier path)
// ─────────────────────────────────────────────────────────────────────

fn render_marker_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample;

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn marker_compiles_on_unit_struct() {
                let _ = Sample;
            }
        }
    }
}

fn render_per_field_smoke(extern_name: &str, spec: &PerFieldDeriveSpec) -> TokenStream {
    let trait_name = &spec.trait_name.0;
    let template = &spec.per_field_template;
    let method_tpl = spec.method_name_template.as_deref();

    // Three method-shape strategies cover the canonical Tier-1 derives.
    // Each strategy explicitly knows what the generated methods look
    // like and asserts they behave; the strategy is selected on the
    // method-name-template + template-body shape.
    let strategy = classify_per_field_template(template, method_tpl);
    match strategy {
        PerFieldStrategy::Getter => render_getter_smoke(extern_name, trait_name),
        PerFieldStrategy::Setter { .. } => render_setter_smoke(extern_name, trait_name),
        PerFieldStrategy::WithBuilder { .. } => render_with_builder_smoke(extern_name, trait_name),
        PerFieldStrategy::AsMut { .. } => render_asmut_smoke(extern_name, trait_name),
        PerFieldStrategy::Replace { .. } => render_replace_smoke(extern_name, trait_name),
        PerFieldStrategy::Take { .. } => render_take_smoke(extern_name, trait_name),
        PerFieldStrategy::Unknown => render_compile_only_smoke(extern_name, trait_name),
    }
}

#[derive(Debug)]
enum PerFieldStrategy {
    /// `pub fn <field>(&self) -> &<T>` — borrowed read.
    Getter,
    /// `pub fn set_<field>(&mut self, v: <T>)` — overwrite.
    Setter { method_tpl: String },
    /// `pub fn with_<field>(mut self, v: <T>) -> Self` — fluent builder.
    WithBuilder { method_tpl: String },
    /// `pub fn <field>_mut(&mut self) -> &mut <T>` — mutable borrow.
    AsMut { method_tpl: String },
    /// `pub fn replace_<field>(&mut self, v: <T>) -> <T>` — swap.
    Replace { method_tpl: String },
    /// `pub fn take_<field>(&mut self) -> <T>` — steal-with-default.
    Take { method_tpl: String },
    /// Template doesn't match any known shape — verifier falls back to
    /// a compile-only smoke that proves the derive expands.
    Unknown,
}

fn classify_per_field_template(template: &str, method_tpl: Option<&str>) -> PerFieldStrategy {
    let body = template.to_lowercase();
    match method_tpl {
        None if body.contains("-> &") && body.contains("&self") => PerFieldStrategy::Getter,
        Some(t) if t.starts_with("with_") && body.contains("-> self") => {
            PerFieldStrategy::WithBuilder {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.starts_with("set_") && body.contains("&mut self") => {
            PerFieldStrategy::Setter {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.starts_with("replace_") && body.contains("mem::replace") => {
            PerFieldStrategy::Replace {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.starts_with("take_") && body.contains("mem::take") => {
            PerFieldStrategy::Take {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.ends_with("_mut") && body.contains("-> &mut") => PerFieldStrategy::AsMut {
            method_tpl: t.to_string(),
        },
        _ => PerFieldStrategy::Unknown,
    }
}

fn render_getter_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub host: String,
            pub port: u16,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn getters_return_borrowed_fields() {
                let s = Sample { host: "h".into(), port: 9 };
                assert_eq!(s.host(), "h");
                assert_eq!(*s.port(), 9);
            }
        }
    }
}

fn render_setter_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(Default, #trait_id)]
        pub struct Sample {
            pub host: String,
            pub port: u16,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn setters_mutate_fields_in_place() {
                let mut s = Sample::default();
                s.set_host("h".into());
                s.set_port(443);
                assert_eq!(s.host, "h");
                assert_eq!(s.port, 443);
            }
        }
    }
}

fn render_with_builder_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(Default, #trait_id)]
        pub struct Sample {
            pub host: String,
            pub port: u16,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn with_builders_return_fluent_self() {
                let s = Sample::default().with_host("h".into()).with_port(9000);
                assert_eq!(s.host, "h");
                assert_eq!(s.port, 9000);
            }
        }
    }
}

fn render_asmut_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub a: i32,
            pub b: String,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn asmut_returns_mutable_borrow() {
                let mut s = Sample { a: 1, b: "hi".into() };
                *s.a_mut() = 42;
                s.b_mut().push('!');
                assert_eq!(s.a, 42);
                assert_eq!(s.b, "hi!");
            }
        }
    }
}

fn render_replace_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub a: i32,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn replace_returns_old_value_and_installs_new() {
                let mut s = Sample { a: 1 };
                let old = s.replace_a(99);
                assert_eq!(old, 1);
                assert_eq!(s.a, 99);
            }
        }
    }
}

fn render_take_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub name: String,
            pub count: u32,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn take_returns_value_and_installs_default() {
                let mut s = Sample { name: "x".into(), count: 7 };
                let n = s.take_name();
                let c = s.take_count();
                assert_eq!(n, "x");
                assert_eq!(c, 7);
                assert_eq!(s.name, "");
                assert_eq!(s.count, 0);
            }
        }
    }
}

fn render_compile_only_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    // Don't know what methods get generated — at least prove the
    // derive expands and the resulting impl block compiles.
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample {
            pub a: i32,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn derive_compiles() {
                let _ = Sample { a: 0 };
            }
        }
    }
}

fn render_enum_fold_smoke(extern_name: &str, spec: &EnumFoldDeriveSpec) -> TokenStream {
    let trait_name = &spec.trait_name.0;
    let tpl = spec.fold_template.to_lowercase();
    if tpl.contains("const all") && tpl.contains("&[#fold]") {
        render_all_variants_smoke(extern_name, trait_name)
    } else if tpl.contains("const count") && tpl.contains("#fold_count") {
        render_variant_count_smoke(extern_name, trait_name)
    } else if tpl.contains("const names") {
        render_variant_names_smoke(extern_name, trait_name)
    } else {
        render_enum_fold_compile_only(extern_name, trait_name)
    }
}

fn render_all_variants_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub enum Sample {
            Red,
            Green,
            Blue,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn all_constant_lists_every_variant() {
                assert_eq!(Sample::ALL.len(), 3);
                assert!(Sample::all().iter().any(|v| matches!(v, Sample::Red)));
                assert!(Sample::all().iter().any(|v| matches!(v, Sample::Green)));
                assert!(Sample::all().iter().any(|v| matches!(v, Sample::Blue)));
            }
        }
    }
}

fn render_variant_count_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub enum Sample {
            A,
            B(u32),
            C { x: i32 },
            D,
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn count_matches_variant_total() {
                assert_eq!(Sample::COUNT, 4);
                assert_eq!(Sample::count(), 4);
            }
        }
    }
}

fn render_variant_names_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub enum Sample {
            Alpha,
            Beta(u8),
            Gamma { n: u32 },
        }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn names_returns_every_variant_label() {
                let names = Sample::names();
                assert_eq!(names.len(), 3);
                assert!(names.contains(&"Alpha"));
                assert!(names.contains(&"Beta"));
                assert!(names.contains(&"Gamma"));
            }
        }
    }
}

fn render_enum_fold_compile_only(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub enum Sample { Unit }

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn enum_fold_derive_compiles() {
                let _ = Sample::Unit;
            }
        }
    }
}

fn render_newtype_smoke(extern_name: &str, spec: &NewtypeDeriveSpec) -> TokenStream {
    let trait_name = &spec.trait_name.0;
    let tpl = spec.impl_template.to_lowercase();
    // Same classify-by-substring pattern as per_field: each known
    // newtype derive emits a specialized smoke; unknown templates fall
    // back to compile-only.
    if tpl.contains("from<#inner_ty>") && tpl.contains("from<#self_name>") {
        render_impl_from_smoke(extern_name, trait_name)
    } else if tpl.contains("asref<#inner_ty>") {
        render_asref_newtype_smoke(extern_name, trait_name)
    } else if tpl.contains("deref for #self_name") {
        render_deref_newtype_smoke(extern_name, trait_name)
    } else if tpl.contains("pub fn inner") && tpl.contains("pub fn into_inner") {
        render_inner_newtype_smoke(extern_name, trait_name)
    } else {
        render_newtype_compile_only_smoke(extern_name, trait_name)
    }
}

fn render_impl_from_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample(pub i32);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn from_inner_constructs_wrapper() {
                let w: Sample = 42i32.into();
                assert_eq!(w.0, 42);
            }
            #[test]
            fn from_wrapper_extracts_inner() {
                let w = Sample(7);
                let n: i32 = w.into();
                assert_eq!(n, 7);
            }
        }
    }
}

fn render_asref_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample(pub String);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn as_ref_borrows_inner() {
                let w = Sample("hi".into());
                let s: &String = w.as_ref();
                assert_eq!(s, "hi");
            }
        }
    }
}

fn render_deref_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample(pub String);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn deref_makes_inner_methods_callable() {
                let w = Sample("hello".into());
                assert_eq!(w.len(), 5);
                assert!(w.starts_with("he"));
            }
        }
    }
}

fn render_inner_newtype_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample(pub i32);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn inner_returns_borrow_into_inner_returns_owned() {
                let w = Sample(42);
                assert_eq!(*w.inner(), 42);
                let w2 = Sample(99);
                assert_eq!(w2.into_inner(), 99);
            }
        }
    }
}

fn render_newtype_compile_only_smoke(extern_name: &str, trait_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");
    quote! {
        use #extern_id::#trait_id;

        #[derive(#trait_id)]
        pub struct Sample(pub i32);

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn newtype_derive_compiles() {
                let _ = Sample(0);
            }
        }
    }
}

fn render_per_variant_smoke(extern_name: &str, spec: &PerVariantDeriveSpec) -> TokenStream {
    let trait_name = &spec.trait_name.0;
    let template = &spec.per_variant_template;
    let method_tpl = spec.method_name_template.as_deref();

    // Per-variant predicate strategy: methods are
    // `is_<variant>(&self) -> bool`. Sample enum has three variants
    // covering unit/tuple/struct shapes.
    let is_predicate = matches!(method_tpl, Some(t) if t.starts_with("is_"))
        && template.contains("matches!");

    let extern_id = format_ident!("{extern_name}");
    let trait_id = format_ident!("{trait_name}");

    if is_predicate {
        render_isvariant_predicate_smoke(extern_name, trait_name)
    } else {
        quote! {
            use #extern_id::#trait_id;

            #[derive(#trait_id)]
            pub enum Sample {
                Unit,
            }

            #[cfg(test)]
            mod tests {
                use super::*;
                #[test]
                fn enum_derive_compiles() {
                    let _ = Sample::Unit;
                }
            }
        }
    }
}

fn render_proc_attr_smoke(extern_name: &str, macro_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let macro_id = format_ident!("{macro_name}");
    quote! {
        use #extern_id::#macro_id;

        #[#macro_id]
        pub struct Sample;

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn proc_attr_compiles() {
                let _ = Sample;
            }
        }
    }
}

fn render_proc_fn_smoke(extern_name: &str, macro_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let macro_id = format_ident!("{macro_name}");
    quote! {
        use #extern_id::#macro_id;

        #macro_id!();

        #[cfg(test)]
        mod tests {
            #[test]
            fn proc_fn_expanded_at_module_scope() {
                // If the macro produced ill-formed Rust, this file wouldn't compile.
            }
        }
    }
}

fn render_macro_rules_smoke(extern_name: &str, macro_name: &str) -> TokenStream {
    let extern_id = format_ident!("{extern_name}");
    let macro_id = format_ident!("{macro_name}");
    quote! {
        pub use #extern_id::#macro_id;

        #[cfg(test)]
        mod tests {
            use super::*;
            #[test]
            fn macro_rules_invokable() {
                // Smoke: invoke the macro with no args; arms cover at least
                // the empty pattern per tatara-rust-verify's MVP contract.
                #macro_id!();
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Cargo.toml renderer — typed CargoManifest, serialized via toml::to_string
// ─────────────────────────────────────────────────────────────────────

fn render_cargo_toml<F>(catalog: &MacroCatalogSpec, repo_path: &F) -> String
where
    F: Fn(&str) -> String,
{
    let mut m = CargoManifest::new(
        Package {
            name: "consumer-verify".into(),
            version: "0.1.0".into(),
            edition: "2024".into(),
            license: "MIT".into(),
            description: format!("Auto-generated verifier for the {} catalog.", catalog.title),
        },
        Some(Lib {
            proc_macro: None,
            path: Some("src/lib.rs".into()),
        }),
    );
    // One path dep per catalog entry.
    for e in &catalog.entries {
        m.add_dep(
            e.crate_name.clone(),
            Dep::Detailed(DetailedDep::path(repo_path(&e.crate_name))),
        );
    }
    // When any entry is a ClosedAxis, the emitted derive references
    // `impl ::shikumi::ClosedAxis`; edition-2018 `::shikumi` resolves
    // against imported crates, so the verify crate needs shikumi as an
    // extern crate to compile + exercise the trait half.
    let needs_shikumi = catalog
        .entries
        .iter()
        .any(|e| matches!(e.spec, CatalogSpec::ClosedAxis { .. }));
    if needs_shikumi {
        m.add_dep(
            "shikumi",
            Dep::Detailed(DetailedDep::git("https://github.com/pleme-io/shikumi")),
        );
    }
    m.to_toml()
        .expect("consumer-verify Cargo manifest is all-string keys; toml::to_string cannot fail")
}

/// Convenience: produce a `consumer-verify/` `FileEntry` set for direct
/// inclusion in any in-memory file-map representation.
#[must_use]
pub fn build_consumer_verify_files<F>(catalog: &MacroCatalogSpec, repo_path: F) -> Vec<FileEntry>
where
    F: Fn(&str) -> String,
{
    build_consumer_verify(catalog, repo_path).files
}

#[cfg(test)]
mod tests {
    use super::*;
    use tatara_rust_ast::Ident;
    use tatara_rust_catalog::{CatalogEntry, CatalogSpec};
    use tatara_rust_derive::{
        ClosedAxisSpec, PerFieldDeriveSpec, PerFieldTarget, PerVariantDeriveSpec, ProcDeriveSpec,
        VariantShape,
    };
    use tatara_rust_snapshot::assert_tokens_contain;

    fn cat() -> MacroCatalogSpec {
        MacroCatalogSpec {
            title: "tests".into(),
            entries: vec![
                CatalogEntry {
                    crate_name: "marker-derive".into(),
                    description: "marker".into(),
                    since: "0.1.0".into(),
                    owner: "pleme-io".into(),
                    verifier_hint: None,
                    spec: CatalogSpec::Derive {
                        spec: ProcDeriveSpec::new("Marker", vec![]),
                    },
                },
                CatalogEntry {
                    crate_name: "getter-all-derive".into(),
                    description: "getter".into(),
                    since: "0.1.0".into(),
                    owner: "pleme-io".into(),
                    verifier_hint: None,
                    spec: CatalogSpec::PerField {
                        spec: PerFieldDeriveSpec {
                            trait_name: Ident::new("GetterAll"),
                            target: PerFieldTarget::NamedStruct,
                            trait_ref: None,
                            per_field_template:
                                "pub fn #field_name(&self) -> &#field_ty { &self.#field_name }"
                                    .into(),
                            method_name_template: None,
                            impl_prelude: None,
                            skip_fields: vec![],
                            field_attribute: None,
                            field_tag: None,
                        },
                    },
                },
                CatalogEntry {
                    crate_name: "is-variant-derive".into(),
                    description: "is-variant".into(),
                    since: "0.1.0".into(),
                    owner: "pleme-io".into(),
                    verifier_hint: None,
                    spec: CatalogSpec::PerVariant {
                        spec: PerVariantDeriveSpec {
                            trait_name: Ident::new("IsVariant"),
                            variant_shape: VariantShape::Any,
                            trait_ref: None,
                            per_variant_template:
                                "pub fn #method_ident(&self) -> bool { matches!(self, #variant_shape_arm) }"
                                    .into(),
                            method_name_template: Some("is_{}".into()),
                            impl_prelude: None,
                        },
                    },
                },
            ],
        }
    }

    fn closed_axis_cat() -> MacroCatalogSpec {
        MacroCatalogSpec {
            title: "closed-axis".into(),
            entries: vec![CatalogEntry {
                crate_name: "pleme-closedaxis-derive".into(),
                description: "closed axis".into(),
                since: "0.1.0".into(),
                owner: "pleme-io".into(),
                verifier_hint: None,
                spec: CatalogSpec::ClosedAxis {
                    spec: ClosedAxisSpec::canonical(),
                },
            }],
        }
    }

    /// Every emitted lib.rs must round-trip through `syn::File` — proves
    /// the ★★ TYPED EMISSION chokepoint accepts whatever the renderers
    /// produce (no malformed quote!{} output reaches consumers).
    fn assert_parses(lib: &str) {
        syn::parse_file(lib).expect("emitted consumer-verify lib.rs must parse");
    }

    #[test]
    fn lib_rs_has_one_module_per_entry() {
        let lib = render_lib_rs(&cat());
        assert_parses(&lib);
        assert_tokens_contain!(&lib, "pub mod marker_derive");
        assert_tokens_contain!(&lib, "pub mod getter_all_derive");
        assert_tokens_contain!(&lib, "pub mod is_variant_derive");
    }

    #[test]
    fn per_field_getter_strategy_picks_borrowed_smoke() {
        let lib = render_lib_rs(&cat());
        assert_parses(&lib);
        assert_tokens_contain!(&lib, "fn getters_return_borrowed_fields()");
        assert_tokens_contain!(&lib, r#"assert_eq!(s.host(), "h")"#);
    }

    #[test]
    fn per_variant_predicate_strategy_picks_event_enum() {
        let lib = render_lib_rs(&cat());
        assert_parses(&lib);
        assert_tokens_contain!(&lib, "fn predicate_returns_true_only_for_own_variant()");
        assert_tokens_contain!(&lib, "Sample::Started");
    }

    #[test]
    fn cargo_toml_has_one_path_dep_per_entry() {
        let scaffold = build_consumer_verify(&cat(), |c| format!("../{c}"));
        let cargo = scaffold
            .files
            .iter()
            .find(|f| f.path == "Cargo.toml")
            .unwrap();
        // Parse the emitted TOML into a typed value, then assert on the
        // structure — never substring-match the syntax (★★ TYPED EMISSION).
        let t: toml::Table = toml::from_str(&cargo.contents).unwrap();
        assert_eq!(
            t["dependencies"]["marker-derive"]["path"].as_str(),
            Some("../marker-derive")
        );
        assert_eq!(
            t["dependencies"]["getter-all-derive"]["path"].as_str(),
            Some("../getter-all-derive")
        );
        assert_eq!(
            t["dependencies"]["is-variant-derive"]["path"].as_str(),
            Some("../is-variant-derive")
        );
        // No closed-axis entry → no shikumi dep.
        assert!(t["dependencies"].get("shikumi").is_none());
        // Plain [lib] (not a proc-macro).
        assert!(t["lib"].get("proc-macro").is_none());
        assert_eq!(t["lib"]["path"].as_str(), Some("src/lib.rs"));
    }

    #[test]
    fn closed_axis_cargo_toml_carries_shikumi_git_dep() {
        let scaffold = build_consumer_verify(&closed_axis_cat(), |c| format!("../{c}"));
        let cargo = scaffold
            .files
            .iter()
            .find(|f| f.path == "Cargo.toml")
            .unwrap();
        let t: toml::Table = toml::from_str(&cargo.contents).unwrap();
        assert_eq!(
            t["dependencies"]["shikumi"]["git"].as_str(),
            Some("https://github.com/pleme-io/shikumi")
        );
    }

    #[test]
    fn closed_axis_smoke_exercises_both_inherent_and_trait_all() {
        let lib = render_lib_rs(&closed_axis_cat());
        assert_parses(&lib);
        // Inherent half.
        assert_tokens_contain!(&lib, "Sample::ALL.len()");
        // Trait half — the full derive output, proven against real shikumi.
        // The turbofish `>::` boundary tokenizes context-dependently
        // (`> ::` vs `>::`), so assert the unambiguous balanced
        // sub-fragment: the qualified trait path `<Sample as
        // ::shikumi::ClosedAxis>` (the load-bearing proof the trait half
        // is exercised) inside the `assert_eq!` macro call.
        assert_tokens_contain!(&lib, "fn trait_impl_all_matches_inherent_all()");
        assert_tokens_contain!(&lib, "<Sample as ::shikumi::ClosedAxis>");
    }

    #[test]
    fn classify_template_recognises_canonical_shapes() {
        assert!(matches!(
            classify_per_field_template(
                "pub fn #field_name(&self) -> &#field_ty { &self.#field_name }",
                None
            ),
            PerFieldStrategy::Getter
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(mut self, v: #field_ty) -> Self { self.#field_name = v; self }",
                Some("with_{}")
            ),
            PerFieldStrategy::WithBuilder { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self, v: #field_ty) { self.#field_name = v; }",
                Some("set_{}")
            ),
            PerFieldStrategy::Setter { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self) -> &mut #field_ty { &mut self.#field_name }",
                Some("{}_mut")
            ),
            PerFieldStrategy::AsMut { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self, v: #field_ty) -> #field_ty { ::std::mem::replace(&mut self.#field_name, v) }",
                Some("replace_{}")
            ),
            PerFieldStrategy::Replace { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self) -> #field_ty where #field_ty: ::std::default::Default { ::std::mem::take(&mut self.#field_name) }",
                Some("take_{}")
            ),
            PerFieldStrategy::Take { .. }
        ));
        assert!(matches!(
            classify_per_field_template("// noise", None),
            PerFieldStrategy::Unknown
        ));
    }
}
