//! `tatara-rust-verify` — auto-emit a `consumer-verify/` crate per
//! `MacroCatalogSpec`. The catalog's own verification harness is
//! itself generated — every emitted derive proves itself in a
//! `cargo test` run alongside the N decorated repos.
//!
//! Per-kind verifier strategy:
//!   - `Derive` (simple marker)       → struct with `#[derive(Trait)]`
//!                                      asserts it compiles.
//!   - `PerField` (getter/setter/builder) → struct with 2 fields,
//!                                      `#[derive(Trait)]`, calls each
//!                                      generated method.
//!   - `PerVariant` (predicate)       → enum with 3 variants,
//!                                      `#[derive(Trait)]`, calls each
//!                                      predicate.
//!   - `ProcAttr` / `ProcFn` / `MacroRules` / `Composite`
//!                                    → MVP: emit `let _ = …;` smoke
//!                                      that proves the macro is
//!                                      importable. Specialized
//!                                      verifiers land as follow-up
//!                                      per-kind variants.

use tatara_rust_ast::{CrateScaffold, FileEntry};
use tatara_rust_catalog::{CatalogEntry, CatalogSpec, MacroCatalogSpec, VerifierHint};
use tatara_rust_derive::{
    EnumFoldDeriveSpec, NewtypeDeriveSpec, PerFieldDeriveSpec, PerVariantDeriveSpec,
};

/// Render a complete `consumer-verify/` Cargo crate scaffold. The
/// caller writes it next to the N decorated repos so that
/// `cargo test -p consumer-verify` exercises every emitted derive.
///
/// `repo_path_template` maps each entry's crate name to the path
/// string the consumer's `Cargo.toml` should use to reach the
/// generated repo — typically `format!("../{name}")` when consumer
/// sits as a workspace member next to the repos.
#[must_use]
pub fn build_consumer_verify(
    catalog: &MacroCatalogSpec,
    repo_path_template: impl Fn(&str) -> String,
) -> CrateScaffold {
    let mut s = CrateScaffold::new("consumer-verify", "0.1.0");
    s.add_file("Cargo.toml", render_cargo_toml(catalog, &repo_path_template));
    s.add_file("src/lib.rs", render_lib_rs(catalog));
    s
}

/// Just the lib.rs body — useful for snapshot tests + diagnostics.
#[must_use]
pub fn render_lib_rs(catalog: &MacroCatalogSpec) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by tatara-rust-verify — exercises every\n");
    out.push_str("//! macro in the catalog. One test module per entry.\n");
    out.push_str("//!\n");
    out.push_str("//! This file is RE-GENERATED on every catalog instantiate;\n");
    out.push_str("//! do not edit by hand.\n\n");

    for entry in &catalog.entries {
        out.push_str(&render_entry_module(entry));
        out.push('\n');
    }
    out
}

fn render_entry_module(entry: &CatalogEntry) -> String {
    let mod_name = entry.crate_name.replace('-', "_");
    let mut out = String::new();
    out.push_str(&format!(
        "/// Verifier for catalog entry `{}` (kind: {}).\n",
        entry.crate_name,
        entry.spec.kind_label()
    ));
    out.push_str(&format!("pub mod {mod_name} {{\n"));
    out.push_str(&render_per_kind_body(entry));
    out.push_str("}\n");
    out
}

fn render_per_kind_body(entry: &CatalogEntry) -> String {
    let extern_name = entry.crate_name.replace('-', "_");

    // **Explicit hint takes precedence.** Removes the fragility of
    // template-text substring matching for catalogs that opt in.
    if let Some(hint) = entry.verifier_hint {
        let trait_name = entry.spec.trait_name_for_verifier().unwrap_or("Unknown");
        return render_by_hint(hint, &extern_name, trait_name);
    }

    // Back-compat path: infer from spec shape + template text.
    match &entry.spec {
        CatalogSpec::Derive { spec } => render_marker_smoke(&extern_name, &spec.trait_name.0),
        CatalogSpec::PerField { spec } => render_per_field_smoke(&extern_name, spec),
        CatalogSpec::PerVariant { spec } => render_per_variant_smoke(&extern_name, spec),
        CatalogSpec::Newtype { spec } => render_newtype_smoke(&extern_name, spec),
        CatalogSpec::EnumFold { spec } => render_enum_fold_smoke(&extern_name, spec),
        CatalogSpec::ProcAttr { spec } => {
            render_proc_attr_smoke(&extern_name, &spec.macro_name.0)
        }
        CatalogSpec::ProcFn { spec } => {
            render_proc_fn_smoke(&extern_name, &spec.macro_name.0)
        }
        CatalogSpec::MacroRules { spec } => {
            render_macro_rules_smoke(&extern_name, &spec.macro_name.0)
        }
        CatalogSpec::Composite { spec } => {
            render_marker_smoke(&extern_name, &spec.bundle_name.0)
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Explicit-hint dispatcher
// ─────────────────────────────────────────────────────────────────────

/// Render a smoke-test body given an explicit `VerifierHint`. Used when
/// the catalog entry opts out of inferred classification.
///
/// The contract: every `VerifierHint` variant maps to exactly one
/// `render_*_smoke` function. Adding a new strategy is a 2-step edit
/// (new variant + new match arm here).
fn render_by_hint(hint: VerifierHint, extern_name: &str, trait_name: &str) -> String {
    match hint {
        VerifierHint::CompileOnly => render_compile_only_smoke(extern_name, trait_name),
        VerifierHint::PerFieldGetter => render_getter_smoke(extern_name, trait_name),
        VerifierHint::PerFieldSetter => render_setter_smoke(extern_name, trait_name, ""),
        VerifierHint::PerFieldWithBuilder => {
            render_with_builder_smoke(extern_name, trait_name, "")
        }
        VerifierHint::PerFieldAsMut => render_asmut_smoke(extern_name, trait_name, ""),
        VerifierHint::PerFieldReplace => render_replace_smoke(extern_name, trait_name, ""),
        VerifierHint::PerFieldTake => render_take_smoke(extern_name, trait_name, ""),
        VerifierHint::PerFieldInvalidatingSetter => {
            render_invalidating_setter_smoke(extern_name, trait_name)
        }
        VerifierHint::PerVariantIsVariant => {
            // Existing per-variant smoke is parameterized by template/method_tpl;
            // for hint dispatch we render the canonical predicate body directly.
            render_isvariant_predicate_smoke(extern_name, trait_name)
        }
        VerifierHint::NewtypeImplFrom => render_impl_from_smoke(extern_name, trait_name),
        VerifierHint::NewtypeAsRef => render_asref_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeDeref => render_deref_newtype_smoke(extern_name, trait_name),
        VerifierHint::NewtypeInner => render_inner_newtype_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldAllVariants => render_all_variants_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldVariantCount => render_variant_count_smoke(extern_name, trait_name),
        VerifierHint::EnumFoldVariantNames => render_variant_names_smoke(extern_name, trait_name),
    }
}

/// Canonical InvalidatingSetter smoke — sample struct includes
/// `last_seqno: u64` (the consumer-contract signal field), and marks
/// the two opt-in fields with `#[invalidating_setter]` per the
/// derive's `field_attribute` contract.
fn render_invalidating_setter_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive(Default, {trait_name})]
    pub struct Sample {{
        #[invalidating_setter]
        pub host: String,
        #[invalidating_setter]
        pub port: u16,
        pub last_seqno: u64,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn invalidating_setters_store_value_and_reset_seqno() {{
            let mut s = Sample::default();
            s.last_seqno = 42;
            s.set_host("h".into());
            assert_eq!(s.host, "h");
            assert_eq!(s.last_seqno, 0, "set_host must reset seqno");

            s.last_seqno = 99;
            s.set_port(443);
            assert_eq!(s.port, 443);
            assert_eq!(s.last_seqno, 0, "set_port must reset seqno");
        }}

        #[test]
        fn signal_field_does_not_get_a_setter() {{
            // If `set_last_seqno` were generated, the trait would
            // shadow direct assignment — but the macro skips the
            // signal field. Confirm by direct access.
            let mut s = Sample::default();
            s.last_seqno = 7;
            assert_eq!(s.last_seqno, 7);
        }}
    }}
"#
    )
}

/// Canonical IsVariant predicate smoke (extracted from `render_per_variant_smoke`'s
/// is-predicate branch so the hint dispatcher can call it directly).
fn render_isvariant_predicate_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{
        Started,
        Stopped(String),
        Tick {{ ms: u64 }},
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn predicate_returns_true_only_for_own_variant() {{
            let s = Sample::Started;
            assert!(s.is_started());
            assert!(!s.is_stopped());
            assert!(!s.is_tick());
        }}
    }}
"#
    )
}

// ─────────────────────────────────────────────────────────────────────
// Per-kind verifier strategies (inferred-classifier path)
// ─────────────────────────────────────────────────────────────────────

fn render_marker_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample;

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn marker_compiles_on_unit_struct() {{
            let _ = Sample;
        }}
    }}
"#
    )
}

fn render_per_field_smoke(extern_name: &str, spec: &PerFieldDeriveSpec) -> String {
    let trait_name = &spec.trait_name.0;
    let template = &spec.per_field_template;
    let method_tpl = spec.method_name_template.as_deref();

    // Three method-shape strategies cover the canonical Tier-1 derives.
    // Each strategy explicitly knows what the generated methods look
    // like and asserts they behave; the strategy is selected on the
    // method-name-template + template-body shape.
    let strategy = classify_per_field_template(template, method_tpl);
    match strategy {
        PerFieldStrategy::Getter => render_getter_smoke(extern_name, trait_name),
        PerFieldStrategy::Setter { method_tpl } => {
            render_setter_smoke(extern_name, trait_name, &method_tpl)
        }
        PerFieldStrategy::WithBuilder { method_tpl } => {
            render_with_builder_smoke(extern_name, trait_name, &method_tpl)
        }
        PerFieldStrategy::AsMut { method_tpl } => {
            render_asmut_smoke(extern_name, trait_name, &method_tpl)
        }
        PerFieldStrategy::Replace { method_tpl } => {
            render_replace_smoke(extern_name, trait_name, &method_tpl)
        }
        PerFieldStrategy::Take { method_tpl } => {
            render_take_smoke(extern_name, trait_name, &method_tpl)
        }
        PerFieldStrategy::Unknown => render_compile_only_smoke(extern_name, trait_name),
    }
}

#[derive(Debug)]
enum PerFieldStrategy {
    /// `pub fn <field>(&self) -> &<T>` — borrowed read.
    Getter,
    /// `pub fn set_<field>(&mut self, v: <T>)` — overwrite.
    Setter { method_tpl: String },
    /// `pub fn with_<field>(mut self, v: <T>) -> Self` — fluent builder.
    WithBuilder { method_tpl: String },
    /// `pub fn <field>_mut(&mut self) -> &mut <T>` — mutable borrow.
    AsMut { method_tpl: String },
    /// `pub fn replace_<field>(&mut self, v: <T>) -> <T>` — swap.
    Replace { method_tpl: String },
    /// `pub fn take_<field>(&mut self) -> <T>` — steal-with-default.
    Take { method_tpl: String },
    /// Template doesn't match any known shape — verifier falls back to
    /// a compile-only smoke that proves the derive expands.
    Unknown,
}

fn classify_per_field_template(template: &str, method_tpl: Option<&str>) -> PerFieldStrategy {
    let body = template.to_lowercase();
    match method_tpl {
        None if body.contains("-> &") && body.contains("&self") => PerFieldStrategy::Getter,
        Some(t) if t.starts_with("with_") && body.contains("-> self") => {
            PerFieldStrategy::WithBuilder {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.starts_with("set_") && body.contains("&mut self") => {
            PerFieldStrategy::Setter {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.starts_with("replace_") && body.contains("mem::replace") => {
            PerFieldStrategy::Replace {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.starts_with("take_") && body.contains("mem::take") => {
            PerFieldStrategy::Take {
                method_tpl: t.to_string(),
            }
        }
        Some(t) if t.ends_with("_mut") && body.contains("-> &mut") => {
            PerFieldStrategy::AsMut {
                method_tpl: t.to_string(),
            }
        }
        _ => PerFieldStrategy::Unknown,
    }
}

fn render_getter_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample {{
        pub host: String,
        pub port: u16,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn getters_return_borrowed_fields() {{
            let s = Sample {{ host: "h".into(), port: 9 }};
            assert_eq!(s.host(), "h");
            assert_eq!(*s.port(), 9);
        }}
    }}
"#
    )
}

fn render_setter_smoke(extern_name: &str, trait_name: &str, _method_tpl: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive(Default, {trait_name})]
    pub struct Sample {{
        pub host: String,
        pub port: u16,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn setters_mutate_fields_in_place() {{
            let mut s = Sample::default();
            s.set_host("h".into());
            s.set_port(443);
            assert_eq!(s.host, "h");
            assert_eq!(s.port, 443);
        }}
    }}
"#
    )
}

fn render_with_builder_smoke(extern_name: &str, trait_name: &str, _method_tpl: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive(Default, {trait_name})]
    pub struct Sample {{
        pub host: String,
        pub port: u16,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn with_builders_return_fluent_self() {{
            let s = Sample::default().with_host("h".into()).with_port(9000);
            assert_eq!(s.host, "h");
            assert_eq!(s.port, 9000);
        }}
    }}
"#
    )
}

fn render_asmut_smoke(extern_name: &str, trait_name: &str, _method_tpl: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample {{
        pub a: i32,
        pub b: String,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn asmut_returns_mutable_borrow() {{
            let mut s = Sample {{ a: 1, b: "hi".into() }};
            *s.a_mut() = 42;
            s.b_mut().push('!');
            assert_eq!(s.a, 42);
            assert_eq!(s.b, "hi!");
        }}
    }}
"#
    )
}

fn render_replace_smoke(extern_name: &str, trait_name: &str, _method_tpl: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample {{
        pub a: i32,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn replace_returns_old_value_and_installs_new() {{
            let mut s = Sample {{ a: 1 }};
            let old = s.replace_a(99);
            assert_eq!(old, 1);
            assert_eq!(s.a, 99);
        }}
    }}
"#
    )
}

fn render_take_smoke(extern_name: &str, trait_name: &str, _method_tpl: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample {{
        pub name: String,
        pub count: u32,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn take_returns_value_and_installs_default() {{
            let mut s = Sample {{ name: "x".into(), count: 7 }};
            let n = s.take_name();
            let c = s.take_count();
            assert_eq!(n, "x");
            assert_eq!(c, 7);
            assert_eq!(s.name, "");
            assert_eq!(s.count, 0);
        }}
    }}
"#
    )
}

fn render_compile_only_smoke(extern_name: &str, trait_name: &str) -> String {
    // Don't know what methods get generated — at least prove the
    // derive expands and the resulting impl block compiles.
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample {{
        pub a: i32,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn derive_compiles() {{
            let _ = Sample {{ a: 0 }};
        }}
    }}
"#
    )
}

fn render_enum_fold_smoke(extern_name: &str, spec: &EnumFoldDeriveSpec) -> String {
    let trait_name = &spec.trait_name.0;
    let tpl = spec.fold_template.to_lowercase();
    if tpl.contains("const all") && tpl.contains("&[#fold]") {
        render_all_variants_smoke(extern_name, trait_name)
    } else if tpl.contains("const count") && tpl.contains("#fold_count") {
        render_variant_count_smoke(extern_name, trait_name)
    } else if tpl.contains("const names") {
        render_variant_names_smoke(extern_name, trait_name)
    } else {
        render_enum_fold_compile_only(extern_name, trait_name)
    }
}

fn render_all_variants_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{
        Red,
        Green,
        Blue,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn all_constant_lists_every_variant() {{
            assert_eq!(Sample::ALL.len(), 3);
            assert!(Sample::all().iter().any(|v| matches!(v, Sample::Red)));
            assert!(Sample::all().iter().any(|v| matches!(v, Sample::Green)));
            assert!(Sample::all().iter().any(|v| matches!(v, Sample::Blue)));
        }}
    }}
"#
    )
}

fn render_variant_count_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{
        A,
        B(u32),
        C {{ x: i32 }},
        D,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn count_matches_variant_total() {{
            assert_eq!(Sample::COUNT, 4);
            assert_eq!(Sample::count(), 4);
        }}
    }}
"#
    )
}

fn render_variant_names_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{
        Alpha,
        Beta(u8),
        Gamma {{ n: u32 }},
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn names_returns_every_variant_label() {{
            let names = Sample::names();
            assert_eq!(names.len(), 3);
            assert!(names.contains(&"Alpha"));
            assert!(names.contains(&"Beta"));
            assert!(names.contains(&"Gamma"));
        }}
    }}
"#
    )
}

fn render_enum_fold_compile_only(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{ Unit }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn enum_fold_derive_compiles() {{
            let _ = Sample::Unit;
        }}
    }}
"#
    )
}

fn render_newtype_smoke(extern_name: &str, spec: &NewtypeDeriveSpec) -> String {
    let trait_name = &spec.trait_name.0;
    let tpl = spec.impl_template.to_lowercase();
    // Same classify-by-substring pattern as per_field: each known
    // newtype derive emits a specialized smoke; unknown templates fall
    // back to compile-only.
    if tpl.contains("from<#inner_ty>") && tpl.contains("from<#self_name>") {
        render_impl_from_smoke(extern_name, trait_name)
    } else if tpl.contains("asref<#inner_ty>") {
        render_asref_newtype_smoke(extern_name, trait_name)
    } else if tpl.contains("deref for #self_name") {
        render_deref_newtype_smoke(extern_name, trait_name)
    } else if tpl.contains("pub fn inner") && tpl.contains("pub fn into_inner") {
        render_inner_newtype_smoke(extern_name, trait_name)
    } else {
        render_newtype_compile_only_smoke(extern_name, trait_name)
    }
}

fn render_impl_from_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample(pub i32);

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn from_inner_constructs_wrapper() {{
            let w: Sample = 42i32.into();
            assert_eq!(w.0, 42);
        }}
        #[test]
        fn from_wrapper_extracts_inner() {{
            let w = Sample(7);
            let n: i32 = w.into();
            assert_eq!(n, 7);
        }}
    }}
"#
    )
}

fn render_asref_newtype_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample(pub String);

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn as_ref_borrows_inner() {{
            let w = Sample("hi".into());
            let s: &String = w.as_ref();
            assert_eq!(s, "hi");
        }}
    }}
"#
    )
}

fn render_deref_newtype_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample(pub String);

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn deref_makes_inner_methods_callable() {{
            let w = Sample("hello".into());
            assert_eq!(w.len(), 5);
            assert!(w.starts_with("he"));
        }}
    }}
"#
    )
}

fn render_inner_newtype_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample(pub i32);

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn inner_returns_borrow_into_inner_returns_owned() {{
            let w = Sample(42);
            assert_eq!(*w.inner(), 42);
            let w2 = Sample(99);
            assert_eq!(w2.into_inner(), 99);
        }}
    }}
"#
    )
}

fn render_newtype_compile_only_smoke(extern_name: &str, trait_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub struct Sample(pub i32);

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn newtype_derive_compiles() {{
            let _ = Sample(0);
        }}
    }}
"#
    )
}

fn render_per_variant_smoke(extern_name: &str, spec: &PerVariantDeriveSpec) -> String {
    let trait_name = &spec.trait_name.0;
    let template = &spec.per_variant_template;
    let method_tpl = spec.method_name_template.as_deref();

    // Per-variant predicate strategy: methods are
    // `is_<variant>(&self) -> bool`. Sample enum has three variants
    // covering unit/tuple/struct shapes.
    let is_predicate = matches!(method_tpl, Some(t) if t.starts_with("is_"))
        && template.contains("matches!");

    if is_predicate {
        format!(
            r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{
        Started,
        Stopped(String),
        Tick {{ ms: u64 }},
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn predicate_returns_true_only_for_own_variant() {{
            let s = Sample::Started;
            assert!(s.is_started());
            assert!(!s.is_stopped());
            assert!(!s.is_tick());
        }}
    }}
"#
        )
    } else {
        format!(
            r#"    use {extern_name}::{trait_name};

    #[derive({trait_name})]
    pub enum Sample {{
        Unit,
    }}

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn enum_derive_compiles() {{
            let _ = Sample::Unit;
        }}
    }}
"#
        )
    }
}

fn render_proc_attr_smoke(extern_name: &str, macro_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{macro_name};

    #[{macro_name}]
    pub struct Sample;

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn proc_attr_compiles() {{
            let _ = Sample;
        }}
    }}
"#
    )
}

fn render_proc_fn_smoke(extern_name: &str, macro_name: &str) -> String {
    format!(
        r#"    use {extern_name}::{macro_name};

    {macro_name}!();

    #[cfg(test)]
    mod tests {{
        #[test]
        fn proc_fn_expanded_at_module_scope() {{
            // If the macro produced ill-formed Rust, this file wouldn't compile.
        }}
    }}
"#
    )
}

fn render_macro_rules_smoke(extern_name: &str, macro_name: &str) -> String {
    let crate_under = extern_name;
    format!(
        r#"    pub use {crate_under}::{macro_name};

    #[cfg(test)]
    mod tests {{
        use super::*;
        #[test]
        fn macro_rules_invokable() {{
            // Smoke: invoke the macro with no args; arms cover at least
            // the empty pattern per tatara-rust-verify's MVP contract.
            {macro_name}!();
        }}
    }}
"#
    )
}

// ─────────────────────────────────────────────────────────────────────
// Cargo.toml renderer
// ─────────────────────────────────────────────────────────────────────

fn render_cargo_toml<F>(catalog: &MacroCatalogSpec, repo_path: &F) -> String
where
    F: Fn(&str) -> String,
{
    let mut deps = String::new();
    for e in &catalog.entries {
        deps.push_str(&format!(
            "{name} = {{ path = \"{path}\" }}\n",
            name = e.crate_name,
            path = repo_path(&e.crate_name)
        ));
    }
    format!(
        r#"# Generated by tatara-rust-verify.
#
# Re-emitted on every `catalog-instantiate` run; do not edit by hand.

[package]
name        = "consumer-verify"
version     = "0.1.0"
edition     = "2024"
description = "Auto-generated verifier for the {title} catalog."
license     = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
{deps}"#,
        title = catalog.title,
        deps = deps
    )
}

/// Convenience: produce a `consumer-verify/` `FileEntry` set for direct
/// inclusion in any in-memory file-map representation.
#[must_use]
pub fn build_consumer_verify_files<F>(
    catalog: &MacroCatalogSpec,
    repo_path: F,
) -> Vec<FileEntry>
where
    F: Fn(&str) -> String,
{
    build_consumer_verify(catalog, repo_path).files
}

#[cfg(test)]
mod tests {
    use super::*;
    use tatara_rust_ast::Ident;
    use tatara_rust_catalog::{CatalogEntry, CatalogSpec};
    use tatara_rust_derive::{
        PerFieldDeriveSpec, PerFieldTarget, PerVariantDeriveSpec, ProcDeriveSpec, VariantShape,
    };

    fn cat() -> MacroCatalogSpec {
        MacroCatalogSpec {
            title: "tests".into(),
            entries: vec![
                CatalogEntry {
                    crate_name: "marker-derive".into(),
                    description: "marker".into(),
                    since: "0.1.0".into(),
                    owner: "pleme-io".into(),
                    verifier_hint: None,
                    spec: CatalogSpec::Derive {
                        spec: ProcDeriveSpec::new("Marker", vec![]),
                    },
                },
                CatalogEntry {
                    crate_name: "getter-all-derive".into(),
                    description: "getter".into(),
                    since: "0.1.0".into(),
                    owner: "pleme-io".into(),
                    verifier_hint: None,
                    spec: CatalogSpec::PerField {
                        spec: PerFieldDeriveSpec {
                            trait_name: Ident::new("GetterAll"),
                            target: PerFieldTarget::NamedStruct,
                            trait_ref: None,
                            per_field_template:
                                "pub fn #field_name(&self) -> &#field_ty { &self.#field_name }"
                                    .into(),
                            method_name_template: None,
                            impl_prelude: None,
                            skip_fields: vec![],
                            field_attribute: None,
                        },
                    },
                },
                CatalogEntry {
                    crate_name: "is-variant-derive".into(),
                    description: "is-variant".into(),
                    since: "0.1.0".into(),
                    owner: "pleme-io".into(),
                    verifier_hint: None,
                    spec: CatalogSpec::PerVariant {
                        spec: PerVariantDeriveSpec {
                            trait_name: Ident::new("IsVariant"),
                            variant_shape: VariantShape::Any,
                            trait_ref: None,
                            per_variant_template:
                                "pub fn #method_ident(&self) -> bool { matches!(self, #variant_shape_arm) }"
                                    .into(),
                            method_name_template: Some("is_{}".into()),
                            impl_prelude: None,
                        },
                    },
                },
            ],
        }
    }

    #[test]
    fn lib_rs_has_one_module_per_entry() {
        let lib = render_lib_rs(&cat());
        assert!(lib.contains("pub mod marker_derive"));
        assert!(lib.contains("pub mod getter_all_derive"));
        assert!(lib.contains("pub mod is_variant_derive"));
    }

    #[test]
    fn per_field_getter_strategy_picks_borrowed_smoke() {
        let lib = render_lib_rs(&cat());
        assert!(lib.contains("getters_return_borrowed_fields"));
        assert!(lib.contains(r#"assert_eq!(s.host(), "h")"#));
    }

    #[test]
    fn per_variant_predicate_strategy_picks_event_enum() {
        let lib = render_lib_rs(&cat());
        assert!(lib.contains("predicate_returns_true_only_for_own_variant"));
        assert!(lib.contains("Sample::Started"));
    }

    #[test]
    fn cargo_toml_has_one_path_dep_per_entry() {
        let scaffold = build_consumer_verify(&cat(), |c| format!("../{c}"));
        let cargo = scaffold
            .files
            .iter()
            .find(|f| f.path == "Cargo.toml")
            .unwrap();
        assert!(cargo.contents.contains(r#"marker-derive = { path = "../marker-derive" }"#));
        assert!(cargo.contents.contains(
            r#"getter-all-derive = { path = "../getter-all-derive" }"#
        ));
        assert!(cargo.contents.contains(
            r#"is-variant-derive = { path = "../is-variant-derive" }"#
        ));
    }

    #[test]
    fn classify_template_recognises_canonical_shapes() {
        assert!(matches!(
            classify_per_field_template(
                "pub fn #field_name(&self) -> &#field_ty { &self.#field_name }",
                None
            ),
            PerFieldStrategy::Getter
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(mut self, v: #field_ty) -> Self { self.#field_name = v; self }",
                Some("with_{}")
            ),
            PerFieldStrategy::WithBuilder { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self, v: #field_ty) { self.#field_name = v; }",
                Some("set_{}")
            ),
            PerFieldStrategy::Setter { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self) -> &mut #field_ty { &mut self.#field_name }",
                Some("{}_mut")
            ),
            PerFieldStrategy::AsMut { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self, v: #field_ty) -> #field_ty { ::std::mem::replace(&mut self.#field_name, v) }",
                Some("replace_{}")
            ),
            PerFieldStrategy::Replace { .. }
        ));
        assert!(matches!(
            classify_per_field_template(
                "pub fn #method_ident(&mut self) -> #field_ty where #field_ty: ::std::default::Default { ::std::mem::take(&mut self.#field_name) }",
                Some("take_{}")
            ),
            PerFieldStrategy::Take { .. }
        ));
        assert!(matches!(
            classify_per_field_template("// noise", None),
            PerFieldStrategy::Unknown
        ));
    }
}
