//! `tatara-rust-publish` — typed GitHub-publish primitive.
//!
//! For each materialized repo (directory containing a Cargo.toml +
//! the standard pleme-io OSS surface), performs the publish sequence:
//!
//!   1. `git init -b main`           (idempotent)
//!   2. `git add .`
//!   3. `git -c user.email=… -c user.name=… commit -m "<msg>"`
//!   4. `gh repo create <org>/<name> --public --description "<desc>" --source=. --push`
//!      OR (if repo already exists) `git push origin main`
//!
//! Batch mode (`publish_all`) iterates a list of repos with fail-fast
//! semantics. Per-repo outcomes are typed via [`PublishOutcome`].
//!
//! Wraps `git` + `gh` CLIs in a typed surface per the fleet's NO
//! SHELL prime directive — invoking typed CLIs is allowed; shell
//! scripts are not.

use serde::Serialize;
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};

/// Per-repo publish input.
#[derive(Clone, Debug, Serialize)]
pub struct RepoPublishSpec {
    /// Local path to the materialized repo (must contain Cargo.toml).
    pub path: PathBuf,
    /// `org/name` form — used in `gh repo create` and as the
    /// remote URL.
    pub full_name: String,
    /// Repo description (`--description`). Capped to GitHub's 350-char
    /// limit on a char boundary before the `gh repo create` call.
    pub description: String,
    /// First-commit message; defaults to `"init: <name> (generated)"`.
    pub commit_message: Option<String>,
}

impl RepoPublishSpec {
    pub fn commit_message(&self) -> String {
        self.commit_message.clone().unwrap_or_else(|| {
            let name = self.full_name.rsplit('/').next().unwrap_or(&self.full_name);
            format!("init: {name} (generated by tatara-rust-ast)")
        })
    }
}

/// Outcome for one repo's publish attempt.
#[derive(Clone, Debug, Serialize)]
pub enum PublishOutcome {
    /// Repo did not exist on GitHub; `gh repo create … --push` succeeded.
    Created { full_name: String },
    /// Repo already existed on GitHub; just pushed the current branch.
    Updated { full_name: String, commits_pushed: usize },
    /// Local repo had nothing to do (already pushed up-to-date,
    /// remote tip matches local).
    UpToDate { full_name: String },
    /// A precondition failed (missing path, no Cargo.toml, etc.).
    Skipped { full_name: String, reason: String },
    /// A subprocess returned non-zero exit.
    Failed {
        full_name: String,
        step: PublishStep,
        exit: Option<i32>,
        stderr: String,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub enum PublishStep {
    GitInit,
    GitAdd,
    GitCommit,
    GhCheckExists,
    GhRepoCreate,
    GitPush,
}

impl PublishStep {
    pub fn label(self) -> &'static str {
        match self {
            Self::GitInit => "git-init",
            Self::GitAdd => "git-add",
            Self::GitCommit => "git-commit",
            Self::GhCheckExists => "gh-check-exists",
            Self::GhRepoCreate => "gh-repo-create",
            Self::GitPush => "git-push",
        }
    }
}

impl PublishOutcome {
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Created { .. } | Self::Updated { .. } | Self::UpToDate { .. })
    }
    pub fn full_name(&self) -> &str {
        match self {
            Self::Created { full_name } | Self::UpToDate { full_name } => full_name,
            Self::Updated { full_name, .. } => full_name,
            Self::Skipped { full_name, .. } => full_name,
            Self::Failed { full_name, .. } => full_name,
        }
    }
}

/// Operator-facing config — user identity for the first commit + any
/// fixed-shape decisions.
#[derive(Clone, Debug)]
pub struct PublishConfig {
    /// `git -c user.email=...` for the first commit.
    pub commit_email: String,
    /// `git -c user.name=...` for the first commit.
    pub commit_name: String,
    /// `--public` (default) or `--private`.
    pub visibility: RepoVisibility,
    /// Default branch name. `main` per the fleet convention.
    pub default_branch: String,
    /// When `true`, treat batch-mode errors as fatal and return at
    /// the first failure. When `false`, continue and aggregate
    /// outcomes.
    pub fail_fast: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RepoVisibility {
    Public,
    Private,
    Internal,
}

impl RepoVisibility {
    fn gh_flag(self) -> &'static str {
        match self {
            Self::Public => "--public",
            Self::Private => "--private",
            Self::Internal => "--internal",
        }
    }
}

impl Default for PublishConfig {
    fn default() -> Self {
        Self {
            commit_email: "fleet@pleme.io".into(),
            commit_name: "pleme-io-fleet".into(),
            visibility: RepoVisibility::Public,
            default_branch: "main".into(),
            fail_fast: true,
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum PublishError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// Run the full publish sequence for one repo.
pub fn publish_repo(
    spec: &RepoPublishSpec,
    cfg: &PublishConfig,
) -> Result<PublishOutcome, PublishError> {
    let full_name = spec.full_name.clone();

    if !spec.path.exists() {
        return Ok(PublishOutcome::Skipped {
            full_name,
            reason: format!("path does not exist: {}", spec.path.display()),
        });
    }
    if !spec.path.join("Cargo.toml").exists() {
        return Ok(PublishOutcome::Skipped {
            full_name,
            reason: "no Cargo.toml at repo root".into(),
        });
    }

    // 1. git init (idempotent).
    let already_initialized = spec.path.join(".git").exists();
    if !already_initialized {
        let out = run(
            "git",
            &["init", "-q", "-b", &cfg.default_branch],
            &spec.path,
        )?;
        if !out.status.success() {
            return Ok(failed_from(&full_name, PublishStep::GitInit, &out));
        }
    }

    // 2. git add . (idempotent — nothing to add is fine).
    let out = run("git", &["add", "."], &spec.path)?;
    if !out.status.success() {
        return Ok(failed_from(&full_name, PublishStep::GitAdd, &out));
    }

    // 3. git commit (only if there are staged changes).
    let pending = run("git", &["status", "--porcelain"], &spec.path)?;
    if !pending.stdout.is_empty() {
        let out = Command::new("git")
            .args([
                "-c",
                &format!("user.email={}", cfg.commit_email),
                "-c",
                &format!("user.name={}", cfg.commit_name),
                "commit",
                "-q",
                "-m",
                &spec.commit_message(),
            ])
            .current_dir(&spec.path)
            .output()?;
        if !out.status.success() {
            return Ok(failed_from(&full_name, PublishStep::GitCommit, &out));
        }
    }

    // 4. Check if the repo already exists on GitHub.
    let exists = run(
        "gh",
        &["repo", "view", &full_name, "--json", "name"],
        &spec.path,
    )?;
    let repo_exists = exists.status.success();

    if !repo_exists {
        // 5a. Create + push in one call. GitHub rejects repo descriptions
        // longer than 350 chars (`createRepository` GraphQL error), so cap
        // it on a char boundary — the catalog's rich one-liners routinely
        // exceed that. The full description still lives in the crate's
        // README / Cargo.toml; the GitHub blurb is just a teaser.
        let gh_description = cap_chars(&spec.description, 350);
        let out = run(
            "gh",
            &[
                "repo",
                "create",
                &full_name,
                cfg.visibility.gh_flag(),
                "--description",
                &gh_description,
                "--source=.",
                "--push",
            ],
            &spec.path,
        )?;
        if !out.status.success() {
            return Ok(failed_from(&full_name, PublishStep::GhRepoCreate, &out));
        }
        return Ok(PublishOutcome::Created { full_name });
    }

    // 5b. Repo exists. Make sure origin is set + push (if there are commits).
    let has_origin = run("git", &["remote", "get-url", "origin"], &spec.path)?
        .status
        .success();
    if !has_origin {
        let _ = run(
            "git",
            &[
                "remote",
                "add",
                "origin",
                &format!("git@github.com:{full_name}.git"),
            ],
            &spec.path,
        )?;
    }

    // Count local commits vs remote (best-effort).
    let push = run("git", &["push", "-u", "origin", &cfg.default_branch], &spec.path)?;
    if !push.status.success() {
        // Distinguish "nothing to push" from real failure.
        let stderr = String::from_utf8_lossy(&push.stderr).to_string();
        if stderr.contains("Everything up-to-date") {
            return Ok(PublishOutcome::UpToDate { full_name });
        }
        return Ok(failed_from(&full_name, PublishStep::GitPush, &push));
    }

    Ok(PublishOutcome::Updated {
        full_name,
        commits_pushed: 1, // we don't bother counting — `git push -u` already reports
    })
}

/// Run the publish sequence for every spec in `specs`. Fail-fast on
/// the first failure when `cfg.fail_fast` is true; otherwise aggregate.
pub fn publish_all(
    specs: &[RepoPublishSpec],
    cfg: &PublishConfig,
) -> Result<BatchOutcome, PublishError> {
    let mut results: Vec<PublishOutcome> = Vec::with_capacity(specs.len());
    let mut stopped = false;
    for s in specs {
        let oc = publish_repo(s, cfg)?;
        let failed = matches!(oc, PublishOutcome::Failed { .. });
        results.push(oc);
        if cfg.fail_fast && failed {
            stopped = true;
            break;
        }
    }
    Ok(BatchOutcome {
        results,
        stopped_at_failure: stopped,
    })
}

#[derive(Debug, Serialize)]
pub struct BatchOutcome {
    pub results: Vec<PublishOutcome>,
    pub stopped_at_failure: bool,
}

impl BatchOutcome {
    pub fn success_count(&self) -> usize {
        self.results.iter().filter(|o| o.is_success()).count()
    }
    pub fn failed_count(&self) -> usize {
        self.results
            .iter()
            .filter(|o| matches!(o, PublishOutcome::Failed { .. }))
            .count()
    }
    pub fn all_succeeded(&self) -> bool {
        !self.stopped_at_failure && self.failed_count() == 0
    }
}

// ─────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────

fn run(program: &str, args: &[&str], cwd: &Path) -> std::io::Result<Output> {
    Command::new(program)
        .args(args)
        .current_dir(cwd)
        .stderr(Stdio::piped())
        .stdout(Stdio::piped())
        .output()
}

/// Truncate `s` to at most `max` chars on a UTF-8 char boundary. Used to
/// fit a catalog description into GitHub's 350-char repo-description limit
/// without panicking on multi-byte boundaries (descriptions contain `—`,
/// `…`, etc.). Returns `s` unchanged when already within `max`.
fn cap_chars(s: &str, max: usize) -> String {
    match s.char_indices().nth(max) {
        None => s.to_owned(),
        Some((byte_idx, _)) => s[..byte_idx].to_owned(),
    }
}

fn failed_from(full_name: &str, step: PublishStep, out: &Output) -> PublishOutcome {
    PublishOutcome::Failed {
        full_name: full_name.into(),
        step,
        exit: out.status.code(),
        stderr: String::from_utf8_lossy(&out.stderr).into_owned(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn step_labels_are_stable() {
        assert_eq!(PublishStep::GitInit.label(), "git-init");
        assert_eq!(PublishStep::GhRepoCreate.label(), "gh-repo-create");
    }

    #[test]
    fn cap_chars_respects_limit_and_char_boundaries() {
        assert_eq!(cap_chars("short", 350), "short");
        // Exactly at the limit is unchanged.
        let s40 = "a".repeat(40);
        assert_eq!(cap_chars(&s40, 40), s40);
        // Over the limit truncates to `max` chars.
        let s400 = "b".repeat(400);
        assert_eq!(cap_chars(&s400, 350).chars().count(), 350);
        // Multi-byte chars never split mid-codepoint (would panic on a
        // byte-index slice). Each `—` is 3 bytes; cap at 2 chars = 6 bytes.
        assert_eq!(cap_chars("—————", 2), "——");
    }

    #[test]
    fn visibility_flags_match_gh_cli_surface() {
        assert_eq!(RepoVisibility::Public.gh_flag(), "--public");
        assert_eq!(RepoVisibility::Private.gh_flag(), "--private");
        assert_eq!(RepoVisibility::Internal.gh_flag(), "--internal");
    }

    #[test]
    fn outcome_is_success_inspects_variant() {
        assert!(PublishOutcome::Created {
            full_name: "x/y".into()
        }
        .is_success());
        assert!(PublishOutcome::Updated {
            full_name: "x/y".into(),
            commits_pushed: 1
        }
        .is_success());
        assert!(PublishOutcome::UpToDate {
            full_name: "x/y".into()
        }
        .is_success());
        assert!(!(PublishOutcome::Skipped {
            full_name: "x/y".into(),
            reason: "no cargo".into()
        })
        .is_success());
        assert!(!(PublishOutcome::Failed {
            full_name: "x/y".into(),
            step: PublishStep::GitInit,
            exit: Some(1),
            stderr: String::new()
        })
        .is_success());
    }

    #[test]
    fn default_commit_message_uses_short_name() {
        let s = RepoPublishSpec {
            path: PathBuf::from("/tmp"),
            full_name: "pleme-io/foo-derive".into(),
            description: "x".into(),
            commit_message: None,
        };
        assert_eq!(
            s.commit_message(),
            "init: foo-derive (generated by tatara-rust-ast)"
        );
    }

    #[test]
    fn custom_commit_message_overrides_default() {
        let s = RepoPublishSpec {
            path: PathBuf::from("/tmp"),
            full_name: "pleme-io/foo-derive".into(),
            description: "x".into(),
            commit_message: Some("my msg".into()),
        };
        assert_eq!(s.commit_message(), "my msg");
    }

    #[test]
    fn skipped_missing_path_returns_skipped() {
        let s = RepoPublishSpec {
            path: PathBuf::from("/nonexistent/path/that/does/not/exist"),
            full_name: "x/y".into(),
            description: "x".into(),
            commit_message: None,
        };
        let cfg = PublishConfig::default();
        let oc = publish_repo(&s, &cfg).unwrap();
        assert!(matches!(
            oc,
            PublishOutcome::Skipped { reason, .. } if reason.contains("does not exist")
        ));
    }

    #[test]
    fn skipped_no_cargo_toml_returns_skipped() {
        let tmp = std::env::temp_dir().join(format!("tatara-publish-no-cargo-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        let s = RepoPublishSpec {
            path: tmp.clone(),
            full_name: "x/y".into(),
            description: "x".into(),
            commit_message: None,
        };
        let cfg = PublishConfig::default();
        let oc = publish_repo(&s, &cfg).unwrap();
        assert!(matches!(
            oc,
            PublishOutcome::Skipped { reason, .. } if reason.contains("Cargo.toml")
        ));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn batch_empty_input_succeeds() {
        let cfg = PublishConfig::default();
        let b = publish_all(&[], &cfg).unwrap();
        assert!(b.all_succeeded());
        assert_eq!(b.success_count(), 0);
        assert_eq!(b.failed_count(), 0);
        assert!(!b.stopped_at_failure);
    }
}
