//! Materialize a `RepoSpec`, write to disk, prove every OSS-publish
//! artifact is present and the README + LICENSE reference the right
//! crate.

use std::path::PathBuf;
use tatara_rust_ast::CrateScaffold;
use tatara_rust_repo::RepoSpec;

fn scaffold(name: &str) -> CrateScaffold {
    let mut s = CrateScaffold::new(name, "0.1.0");
    s.add_file(
        "Cargo.toml",
        format!("[package]\nname = \"{name}\"\nversion = \"0.1.0\"\n"),
    );
    s.add_file("src/lib.rs", "// generated proc-macro\n".to_string());
    s
}

#[test]
fn defaults_attach_full_oss_publish_surface_on_disk() {
    let tmp: PathBuf = std::env::temp_dir().join(format!(
        "tatara-rust-repo-decorations-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();

    let spec = RepoSpec::defaults_for(
        scaffold("foo-derive"),
        "foo-derive",
        "https://github.com/pleme-io/foo-derive",
        "Foo derive macro generated by tatara-rust-ast.",
    );
    let compiled = spec.compile();
    let root = tmp.join("foo-derive");
    compiled.write_to(&root).unwrap();

    let must_exist = [
        "Cargo.toml",
        "src/lib.rs",
        "flake.nix",
        "caixa.lisp",
        ".github/workflows/auto-release.yml",
        "clippy.toml",
        "LICENSE",
        ".gitignore",
        "rust-toolchain.toml",
        "README.md",
    ];
    for rel in must_exist {
        let p = root.join(rel);
        assert!(p.exists(), "missing {}", p.display());
    }

    // Spot-check: README references crate name + GitHub slug + crates.io badge.
    let readme = std::fs::read_to_string(root.join("README.md")).unwrap();
    assert!(readme.contains("# foo-derive"));
    assert!(readme.contains("pleme-io/foo-derive"));
    assert!(readme.contains("crates.io/crates/foo-derive"));

    // clippy.toml carries the format-ban.
    let clippy = std::fs::read_to_string(root.join("clippy.toml")).unwrap();
    assert!(clippy.contains(r#"disallowed-macros = ["std::format"]"#));

    // auto-release.yml references the substrate per-language reusable.
    let yml = std::fs::read_to_string(root.join(".github/workflows/auto-release.yml")).unwrap();
    assert!(yml.contains("uses: pleme-io/substrate/.github/workflows/cargo-auto-release.yml"));

    // caixa.lisp declares Biblioteca kind in pleme-doc-gen shape.
    let caixa = std::fs::read_to_string(root.join("caixa.lisp")).unwrap();
    assert!(caixa.contains("(defcaixa foo-derive"));
    assert!(caixa.contains(r#":kind         "Biblioteca""#));
    assert!(caixa.contains(r#":ecosystem    "rust-single-crate""#));

    let _ = std::fs::remove_dir_all(&tmp);
}
