//! `tatara-rust-proc-attr` — L2 authoring surface for **attribute** proc-macros.
//!
//! One typed [`ProcAttrSpec`] value → one complete proc-macro crate
//! that exposes `#[my_attr(args)] item`. Same Spec → [`CompileToCrate`]
//! template as `tatara-rust-derive`.
//!
//! Today's emit shape is **passthrough + prelude**: the macro takes the
//! annotated item, prepends a literal Rust prelude (e.g.
//! `#[inline] #[must_use]`), and re-emits the item unchanged. Sufficient
//! for the "instrument every fn" / "add #[doc(hidden)] everywhere"
//! family. Richer transforms (item rewriting, AST surgery) land in v0.2
//! by extending the `transform` enum.
//!
//! ```
//! use tatara_rust_ast::{CompileToCrate, Ident};
//! use tatara_rust_proc_attr::{AttrTransform, ProcAttrSpec};
//!
//! let spec = ProcAttrSpec {
//!     macro_name: Ident::new("instrumented"),
//!     transform: AttrTransform::PrependPrelude {
//!         prelude_tokens: "#[inline]".into(),
//!     },
//! };
//! let scaffold = spec.compile_to_crate("instrumented-attr").unwrap();
//! assert!(scaffold.to_files().contains_key("src/lib.rs"));
//! ```

use serde::{Deserialize, Serialize};
use tatara_rust_ast::{AstError, CompileToCrate, CrateScaffold, Ident};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProcAttrSpec {
    pub macro_name: Ident,
    pub transform: AttrTransform,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum AttrTransform {
    /// Pass the annotated item through unchanged, but emit `prelude_tokens`
    /// immediately before it. Raw Rust source; rendered with `quote!{}`.
    PrependPrelude { prelude_tokens: String },
}

impl ProcAttrSpec {
    fn fn_name(&self) -> String {
        snake_case(&self.macro_name.0)
    }
}

impl CompileToCrate for ProcAttrSpec {
    fn compile_to_crate(&self, crate_name: &str) -> Result<CrateScaffold, AstError> {
        let mut scaffold = CrateScaffold::new(crate_name, "0.1.0");
        scaffold.add_file("Cargo.toml", render_cargo_toml(crate_name));
        scaffold.add_file("src/lib.rs", render_lib_rs(self));
        Ok(scaffold)
    }
}

fn render_cargo_toml(crate_name: &str) -> String {
    tatara_rust_ast::render_proc_macro_cargo_toml(
        crate_name,
        "Proc-macro attribute crate emitted from a tatara-rust-proc-attr ProcAttrSpec.",
    )
}

fn render_lib_rs(spec: &ProcAttrSpec) -> String {
    let mac = &spec.macro_name.0;
    let fn_name = spec.fn_name();
    let body = match &spec.transform {
        AttrTransform::PrependPrelude { prelude_tokens } => format!(
            r#"    let item: proc_macro2::TokenStream = item.into();
    let prelude: proc_macro2::TokenStream = {prelude:?}.parse().unwrap_or_default();
    let expanded = quote! {{ #prelude #item }};
    TokenStream::from(expanded)"#,
            prelude = prelude_tokens
        ),
    };

    format!(
        r#"// GENERATED by tatara-rust-proc-attr from a ProcAttrSpec.
use proc_macro::TokenStream;
use quote::quote;

#[proc_macro_attribute]
pub fn {fn_name}(_attr: TokenStream, item: TokenStream) -> TokenStream {{
{body}
}}

// Re-export the attribute name so consumers `use {pkg_under}::{mac};`
// works as `#[{mac}]`.
"#,
        pkg_under = "crate_will_be_named_after_package"
    )
}

fn snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> ProcAttrSpec {
        ProcAttrSpec {
            macro_name: Ident::new("instrumented"),
            transform: AttrTransform::PrependPrelude {
                prelude_tokens: "#[inline]".into(),
            },
        }
    }

    #[test]
    fn compiles_to_lib_and_cargo() {
        let scaffold = sample().compile_to_crate("instrumented-attr").unwrap();
        let files = scaffold.to_files();
        assert!(files.contains_key("Cargo.toml"));
        assert!(files.contains_key("src/lib.rs"));
    }

    #[test]
    fn lib_rs_declares_attribute_fn() {
        let scaffold = sample().compile_to_crate("instrumented-attr").unwrap();
        let lib = scaffold.to_files().get("src/lib.rs").unwrap().clone();
        assert!(lib.contains("#[proc_macro_attribute]"));
        assert!(lib.contains("pub fn instrumented"));
        assert!(lib.contains("#[inline]"));
    }

    #[test]
    fn cargo_toml_marks_proc_macro() {
        let scaffold = sample().compile_to_crate("instrumented-attr").unwrap();
        let toml = scaffold.to_files().get("Cargo.toml").unwrap().clone();
        assert!(toml.contains("proc-macro = true"));
    }

    #[test]
    fn snake_case_handles_camel() {
        assert_eq!(snake_case("MyAttr"), "my_attr");
        assert_eq!(snake_case("instrumented"), "instrumented");
    }

    #[test]
    fn serde_roundtrip() {
        let s = sample();
        let j = serde_json::to_string(&s).unwrap();
        let back: ProcAttrSpec = serde_json::from_str(&j).unwrap();
        assert_eq!(s, back);
    }
}
