//! `tatara-rust-proc-fn` — L2 authoring surface for **function-like** proc-macros.
//!
//! One typed [`ProcFnSpec`] value → one complete proc-macro crate that
//! exposes `my_macro!(token-stream)`. Same Spec → [`CompileToCrate`]
//! template as `tatara-rust-derive` and `tatara-rust-proc-attr`.
//!
//! Today's emit shape is **literal-prelude + input-passthrough**:
//! `my_macro!(<tokens>)` expands to `<prelude_tokens> <tokens>`. Sufficient
//! for the "wrap every invocation in a known shape" family (e.g. `sql!`
//! pre-prefixing query helpers). Richer transforms land via the same
//! enum-extension path as proc-attr.
//!
//! ```
//! use tatara_rust_ast::{CompileToCrate, Ident};
//! use tatara_rust_proc_fn::{FnTransform, ProcFnSpec};
//!
//! let spec = ProcFnSpec {
//!     macro_name: Ident::new("say_hi"),
//!     transform: FnTransform::PrependPrelude {
//!         prelude_tokens: "println!(\"hi\");".into(),
//!     },
//! };
//! let scaffold = spec.compile_to_crate("say-hi-fn").unwrap();
//! assert!(scaffold.to_files().contains_key("src/lib.rs"));
//! ```

use serde::{Deserialize, Serialize};
use tatara_rust_ast::{AstError, CompileToCrate, CrateScaffold, Ident};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProcFnSpec {
    pub macro_name: Ident,
    pub transform: FnTransform,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum FnTransform {
    /// `my_macro!(<input>)` → `<prelude> <input>`. Raw token-stream concat.
    PrependPrelude { prelude_tokens: String },
}

impl CompileToCrate for ProcFnSpec {
    fn compile_to_crate(&self, crate_name: &str) -> Result<CrateScaffold, AstError> {
        let mut scaffold = CrateScaffold::new(crate_name, "0.1.0");
        scaffold.add_file("Cargo.toml", render_cargo_toml(crate_name));
        scaffold.add_file("src/lib.rs", render_lib_rs(self));
        Ok(scaffold)
    }
}

fn render_cargo_toml(crate_name: &str) -> String {
    tatara_rust_ast::render_proc_macro_cargo_toml(
        crate_name,
        "Proc-macro function-like crate emitted from a tatara-rust-proc-fn ProcFnSpec.",
    )
}

fn render_lib_rs(spec: &ProcFnSpec) -> String {
    let mac = &spec.macro_name.0;
    let body = match &spec.transform {
        FnTransform::PrependPrelude { prelude_tokens } => format!(
            r#"    let input: proc_macro2::TokenStream = input.into();
    let prelude: proc_macro2::TokenStream = {prelude:?}.parse().unwrap_or_default();
    let expanded = quote! {{ #prelude #input }};
    TokenStream::from(expanded)"#,
            prelude = prelude_tokens
        ),
    };
    format!(
        r#"// GENERATED by tatara-rust-proc-fn from a ProcFnSpec.
use proc_macro::TokenStream;
use quote::quote;

#[proc_macro]
pub fn {mac}(input: TokenStream) -> TokenStream {{
{body}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> ProcFnSpec {
        ProcFnSpec {
            macro_name: Ident::new("say_hi"),
            transform: FnTransform::PrependPrelude {
                prelude_tokens: "println!(\"hi\");".into(),
            },
        }
    }

    #[test]
    fn compiles_to_lib_and_cargo() {
        let scaffold = sample().compile_to_crate("say-hi-fn").unwrap();
        let files = scaffold.to_files();
        assert!(files.contains_key("Cargo.toml"));
        assert!(files.contains_key("src/lib.rs"));
    }

    #[test]
    fn lib_rs_declares_proc_macro_fn() {
        let scaffold = sample().compile_to_crate("say-hi-fn").unwrap();
        let lib = scaffold.to_files().get("src/lib.rs").unwrap().clone();
        assert!(lib.contains("#[proc_macro]"));
        assert!(lib.contains("pub fn say_hi(input: TokenStream)"));
        assert!(lib.contains("println!"));
    }

    #[test]
    fn cargo_toml_marks_proc_macro() {
        let scaffold = sample().compile_to_crate("say-hi-fn").unwrap();
        let toml = scaffold.to_files().get("Cargo.toml").unwrap().clone();
        assert!(toml.contains("proc-macro = true"));
    }

    #[test]
    fn serde_roundtrip() {
        let s = sample();
        let j = serde_json::to_string(&s).unwrap();
        let back: ProcFnSpec = serde_json::from_str(&j).unwrap();
        assert_eq!(s, back);
    }
}
